# Generated by Django 3.1.5 on 2021-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0002_auto_20210122_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='datetime',
            field=models.CharField(max_length=150, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='your_job',
            field=models.CharField(max_length=150, verbose_name='شغل شما'),
        ),
    ]
