# Generated by Django 3.1.5 on 2021-01-22 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_home', '0004_sitesetting_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('icon', models.CharField(max_length=100, verbose_name='ای دی ایکون')),
                ('link', models.CharField(max_length=500, verbose_name='لینک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنظیمات لینک',
            },
        ),
    ]
