# Generated by Django 3.1.5 on 2021-01-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0006_auto_20210122_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSkins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'تنظیمات مهارت',
                'verbose_name_plural': 'تنظیمات مهارت ها',
            },
        ),
    ]
