# Generated by Django 3.1.5 on 2021-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0010_siteexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سرویس')),
                ('icon', models.ImageField(upload_to='', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تنظیمات تجربه',
                'verbose_name_plural': 'ماژول تجربه',
            },
        ),
        migrations.AlterField(
            model_name='siteexperience',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='siteexperience',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام تیم یا شرکت'),
        ),
        migrations.AlterField(
            model_name='siteexperience',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='نوع فعالیت'),
        ),
    ]
