# Generated by Django 3.1.5 on 2021-01-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0011_auto_20210123_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteservice',
            options={'verbose_name': 'تنظیمات خدمات', 'verbose_name_plural': 'ماژول خدمات'},
        ),
    ]
