# Generated by Django 3.1.5 on 2021-01-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0012_auto_20210125_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteservice',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='عکس'),
        ),
    ]
