# Generated by Django 3.1.5 on 2021-01-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0013_auto_20210126_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteservice',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
    ]
