# Generated by Django 3.1.5 on 2021-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0014_auto_20210126_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelink',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='ای دی ایکون'),
        ),
    ]
