# Generated by Django 3.1.5 on 2021-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0015_auto_20210126_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelink',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='ای دی ایکون'),
        ),
    ]
