# Generated by Django 3.1.5 on 2021-01-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_home', '0016_auto_20210126_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteeducation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteexperience',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
