# Generated by Django 3.1.5 on 2021-01-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_contact', '0002_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='map',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
