# Generated by Django 3.1.5 on 2021-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_contact', '0003_information_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='map',
            field=models.URLField(),
        ),
    ]
